### PR TITLE
Introduce recursion to find top most controller

### PR DESCRIPTION
**Pull request by dasdom**

### CODE REVIEW

**Review by joemasilotti — CHANGES_REQUESTED** [review]
Thanks for this! Would you mind adding some tests before I merge? If you don’t have bandwidth let me know and I can add them myself.

**Comment by dasdom** [comment]
I don't mind at all. Could you tell me how I can run the tests? If I try in Xcode, they complain that they can't find `RootViewController` and `TableViewController`. What am I missing?

**Comment by joemasilotti** [comment]
That's weird. I just cloned the repo fresh and running the tests from the `Ruka` scheme worked as expected. Are the files not listed under `Support/`?

**Comment by dasdom** [comment]
Sorry, was busy yesterday. I'll have a look today after work.

**Comment by dasdom** [comment]
It was my fault. I opened the Package.swift instead of the Ruka.xcodeproj. A few tests fail. I'll fix those and add tests for my changes.

**Comment by dasdom** [comment]
I have added two tests.

In addition I added async expectations to two existing tests because they failed in my 5 year old MacBook Air. Please have a look and give me feedback if these tests are ok.

**Comment by joemasilotti** [comment]
Oh interesting. Do the tests fail when you run them on `main`, too?

**Comment by dasdom** [comment]
Do you mean when I put all the test onto the main dispatch queue?

**Comment by joemasilotti** [comment]
Ah, no, I actually meant the `main` branch.

**Comment by dasdom** [comment]
Fresh clone of your repository:

Screenshot 2020-12-18 at 20 30 51

MacBook Air (13-inch, Early 2015)
1,6 GHz Dual-Core Intel Core i5
Xcode Version 12.2 (12B45b)

I'm not sure what the reason is for this. When I delay the assertion the test passes:

```swift
func test_dismissesAViewController() throws {
    let controller = RootViewController()
    let app = App(controller: controller, failureBehavior: .doNothing)
    XCTAssertNil(try app.button("Dismiss view controller"))

    try app.button("Present view controller")?.tap()
    XCTAssertNotNil(try app.button("Dismiss view controller"))

    let async = expectation(description: "async")
    try app.button("Dismiss view controller")?.tap()
    DispatchQueue.main.asyncAfter(deadline: .now() + 0.01) {
        async.fulfill()
    }
    wait(for: [async], timeout: 1)
    XCTAssertNil(try app.button("Dismiss view controller"))
}
```

**Comment by joemasilotti** [comment]
Got it, thanks! That's super helpful. I'm going to work on getting `master` working without any waiting (at least in the tests) first.

**Comment by dasdom** [comment]
Looking forward to your solution!

**Comment by joemasilotti** [comment]
OK, I messed around with some custom (slower) waiting for the animations. Can you please give this a run and let me know if the tests pass on your machine? If so then I'll handle the conflicts and merge it in.

**Comment by dasdom** [comment]
I had to adjust the animation duration to make the tests pass on my MacBook Air. Now all tests are green.

**Comment by joemasilotti** [comment]
Merged in! Thanks for this @dasdom :D

**Pull request merged**
